stages:
  - build
  - publish-image
  - deploy

.build:
  stage: build
  image: openjdk:21-slim
  artifacts:
    expire_in: 1 days
    paths:
      - target/*.jar
  script:
    - apt-get update && apt-get install -y maven
    - mvn clean install -DskipTests --no-transfer-progress

build-develop:
  environment: develop
  extends: .build
  only:
    - develop

build-main:
  environment: main
  extends: .build
  only:
    - main

#publish-image:
#  stage: publish-image
#  image:
#    name: gcr.io/kaniko-project/executor:debug
#    entrypoint: [ '' ]
#  script:
#    - mkdir -p /kaniko/.docker
#    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "gitlab-ci-token" "${CI_JOB_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#    - >-
#      /kaniko/executor
#      --cache=true
#      --context "."
#      --dockerfile "Dockerfile"
#      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
#  only:
#    - develop
#    - main

publish-image:
  stage: publish-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ '' ]
  script:
    - apk update && apk add git
    - git clone git@gitlab.com:batullina-agona-2024.git
    - cd batullina-agona-2024/Agona-05
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "gitlab-ci-token" "${CI_JOB_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true
      --context batullina-agona-2024/Agona-05
      --dockerfile batullina-agona-2024/Agona-05/Dockerfile 
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - develop
    - main

.deploy:
  image: docker:19.03.8-dind
  stage: deploy
  dependencies:
    - build-develop
  script:
    - cp target/Agona-05-1.0-SNAPSHOT.jar ./app/
    - ./deploy.sh

deploy-develop:
  environment: develop
  extends: .deploy
  variables:
    BRANCH: develop
    SSH: develop
    TAG: develop
  only:
    - develop

deploy-main:
  environment: main
  extends: .deploy
  variables:
    BRANCH: main
    SSH: main
    TAG: main
  only:
    - main