version: '3.7'

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=default.local
      - VIRTUAL_HOST=main.example.com
      - VIRTUAL_PORT=80
      - ENABLE_IPV6=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/var/www/html
      - ./certs:/etc/letsencrypt

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    command: -watch

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx-proxy-acme:
    image: jwilder/nginx-proxy-acme
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_HOST=default.local
      - VIRTUAL_HOST=main.example.com
      - EMAIL=your-email@example.com
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

volumes:
  portainer_data:
