services:
  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=default.local
      - VIRTUAL_HOST=develop.example.com
      - VIRTUAL_PORT=80
      - ENABLE_IPV6=false
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/var/www/html
      - ./certs:/etc/letsencrypt

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    command: -watch

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_HOST=default.local
      - VIRTUAL_HOST=develop.example.com
      - EMAIL=batullina2005@gmail.com
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/letsencrypt
    ports:
      - "8081:80"
      - "444:443"

  agona-app:
    image: registry.gitlab.com/ekaterinabatullina/infrastructure2/agona-05:develop
    container_name: agona-05
    restart: always
    environment:
      - VIRTUAL_HOST=develop.example.com
      - VIRTUAL_PORT=8080
    ports:
      - "8082:8080"

volumes:
  portainer_data: