services:
  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=default.local
      - VIRTUAL_HOST=main.example.com
      - VIRTUAL_PORT=80
      - ENABLE_IPV6=false
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/var/www/html
      - ./certs:/etc/letsencrypt

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    command: -watch

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_HOST=default.local
      - VIRTUAL_HOST=main.example.com
      - EMAIL=batullina2005@gmail.com
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/letsencrypt
    ports:
      - "8081:80"
      - "444:443"

  agona-app:
    image: registry.gitlab.com/ekaterinabatullina/infrastructure2/user-service/user-service-impl:main
    container_name: user-service-impl
    restart: on-failure
    environment:
      - VIRTUAL_HOST=main.example.com
      - VIRTUAL_PORT=8080
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=Ekaterina
      - DB_PASSWORD=eka_rina16
      - DB_NAME=agona_db
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: Ekaterina
      POSTGRES_PASSWORD: eka_rina16
      POSTGRES_DB: agona_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  portainer_data:
  postgres_data:

networks:
  app_network:
    driver: bridge