spring.datasource.url=jdbc:postgresql://postgres_db:5432/agona_db
spring.datasource.username=Ekaterina
spring.datasource.password=eka_rina16
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10